### ISSUE TITLE
libQt5Core

### ISSUE THREAD

**Issue by bronze** [ItzSelenux/papirus-folders-gui#1]
Hi
tried installing and i got an error  
`./papirus-folders-gui.sh: /lib/x86_64-linux-gnu/libQt5Core.so.5: version 'Qt_5.15' not found (required by ./papirus-folders-gui.sh)`

any tips?

**Comment by ItzSelenux** [comment]
do you have Qt5 base?, what OS you are using?

**Comment by bronze** [comment]
Linux, Pop OS! 20.10

**Comment by HanM23** [comment]
Hi,
I reported my issues on AUR. https://aur.archlinux.org/packages/papirus-folders-gui/#comment-824961

My desktop environment is XFCE and qt5-tools is a missing dependency, it requires it when building. Then, "Kill File Manager" feature does not work with Thunar (4.16.8), i have to logout/login to see changes
