### ISSUE TITLE
Missing dependency : qt5-tools | Kill File Manager does not work with Thunar

### ISSUE THREAD

**Issue by HanM23** [ItzSelenux/papirus-folders-gui#2]
Hi,
I reported my issues on AUR. https://aur.archlinux.org/packages/papirus-folders-gui/#comment-824961
There are 2 issues:

1) My desktop environment is XFCE and qt5-tools is a missing dependency, it requires it when building. 

2) "Kill File Manager" feature does not work with Thunar (4.16.8), i have to logout/login to see changes
--> For this one, there is a small error in the source code 

void MainWindow::on_kill_clicked()
{
    folder->start("killall caja dolphin nautilus nemo pcmanfm spacefm thunar");
}

--> Does not work with Thunar, Thunar must be written with a capital "T"  because it starts as a daemon.

**Comment by ItzSelenux** [comment]
Sorry for taking time to respond, thanks for clarifying the error in thunar, in a short time I will launch an update
you're correcting the bug, I'm not really sure why the qt5-tools thing happened

**Comment by HanM23** [comment]
Well, to be more accurate.
When you boot on Linux with XFCE, Thunar starts as a daemon, with a capital "T".
It's there : /etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfce4-session.xml
Then, if you kill the daemon and run Thunar by clicking a desktop file in the start menu, you do not run it as a daemon anymore, and in this case, there is no more capital "T" in the process.

Regarding the qt5-tools dependency, you mean you don't need it on your distro ?

**Comment by ItzSelenux** [comment]
i made the first versions on Manjaro and Arch, and i not have problems with that, i actually  use Artix and the same history, it is supposed that with qt5-base and cmake the compilation should be done correctly, in any case in the AUR it is also papirus-folders-gui-bin

**Comment by HanM23** [comment]
I installed the last Manjaro ISO in a VM, XFCE minimal, opened pamac and installed papirus-folder-gui, i get this when building, in case you want to see the error i get :

CMake Error at /usr/lib64/cmake/Qt5/Qt5Config.cmake:28 (find_package):
  Could not find a package configuration file provided by "Qt5LinguistTools"
  with any of the following names:

    Qt5LinguistToolsConfig.cmake
    qt5linguisttools-config.cmake

  Add the installation prefix of "Qt5LinguistTools" to CMAKE_PREFIX_PATH or
  set "Qt5LinguistTools_DIR" to a directory containing one of the above
  files.  If "Qt5LinguistTools" provides a separate development package or
  SDK, be sure it has been installed.
Call Stack (most recent call first):
  CMakeLists.txt:28 (find_package)

Then, i installed qt5-tools, and no issue anymore.
-- Configuring incomplete, errors occurred!
See also "/var/tmp/pamac-build-barracuda/papirus-folders-gui/src/papirus-folders-gui-1.4/papirus-folders-gui/CMakeFiles/CMakeOutput.log".
==> ERROR: A failure occurred in build().
    Aborting...

**Comment by HanM23** [comment]
Do not know why you closed the issues i reported. I took time to do it, to find out what was the causes of those issues, to make test again on a fresh vanilla Distro.
As far as i know, they are reals ones and not corrected. Not fair as a open source community member, and you are discouraging people to share
