### ISSUE TITLE
Icons for app

### ISSUE THREAD

**Issue by varlesh** [ItzSelenux/papirus-folders-gui#3]
![image](https://user-images.githubusercontent.com/8083855/135706530-c61b221a-c43a-4b49-9ce1-c92fb9b13ae9.png)
[icons.zip](https://github.com/ItzSelenux/papirus-folders-gui/files/7270978/icons.zip)

**Comment by varlesh** [comment]
Also will be good have install script to:

- ~/.local/bin/papirus-folders-gui
- ~/.local/share/applications/papirus-folders-gui.desktop

```
[Desktop Entry]
Exec=papirus-folders-gui
Icon=papirus-folders-gui
Type=Application
Name=papirus-folders GUI
Comment=GUI Tool for papirus-folders
Categories=Qt;Settings;
StartupWMClass=papirus-folders-gui
```

**Comment by ItzSelenux** [comment]
Hi, sorry for the late reply, I'll take those icons into account C:
